### ISSUE TITLE
Fails at "npm run server"

### ISSUE THREAD

**Issue by bresson** [DrBoolean/classroom-coding#1]
I get the following message when entering "npm run server" into the terminal. Thoughts?
- message in terminal:
  sh: babel-node: command not found
  ...
- message in npm debug:
  0 info it worked if it ends with ok
  1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'server' ]
  2 info using npm@2.14.7
  3 info using node@v4.2.3
  4 verbose run-script [ 'preserver', 'server', 'postserver' ]
  5 info preserver collagr@0.1.0
  6 info server collagr@0.1.0
  7 verbose unsafe-perm in lifecycle true
  8 info collagr@0.1.0 Failed to exec server script
  9 verbose stack Error: collagr@0.1.0 server: `babel-node src/backend/app.js`
  9 verbose stack spawn ENOENT
  9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
  9 verbose stack     at emitTwo (events.js:87:13)
  9 verbose stack     at ChildProcess.emit (events.js:172:7)
  9 verbose stack     at maybeClose (internal/child_process.js:818:16)
  9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  10 verbose pkgid collagr@0.1.0
  11 verbose cwd /Users/KRM-MacBookPro/Copy/_projects/_experiments/react-functional-drboolean/classroom-coding
  12 error Darwin 15.2.0
  13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
  14 error node v4.2.3
  15 error npm  v2.14.7
  16 error file sh
  17 error code ELIFECYCLE
  18 error errno ENOENT
  19 error syscall spawn
  20 error collagr@0.1.0 server: `babel-node src/backend/app.js`
  20 error spawn ENOENT
  21 error Failed at the collagr@0.1.0 server script 'babel-node src/backend/app.js'.

**Comment by bresson** [comment]
Installing the following seems to help:
npm install --save-dev babel-cli
